# Generated by Django 6.1.1 on 2026-10-05 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('access_staff', 'Puede acceder a administración interna'), ('access_kitchen', 'Puede acceder a cocina'), ('access_bar', 'Puede acceder a barra')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
