# Generated by Django 6.1.1 on 2026-10-09 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_product_allergens_product_ingredients_and_more'),
        ('orders', '0003_order_order_valid_production_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(unique=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balance', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(null=True)),
                ('notes', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_closings', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_openings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PRODUCTION', 'Producción'), ('SALE', 'Venta (demostración)'), ('RETURN', 'Cancelación sin preparar'), ('CANCEL_WASTE', 'Cancelación preparada'), ('WASTE', 'Merma / descarte'), ('ADJUST', 'Ajuste'), ('COUNT', 'Conciliación de cierre')], max_length=20)),
                ('delta', models.IntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('reversal_of', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.movement')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='stock.shift')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ShiftItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sku', models.CharField(max_length=50)),
                ('initial', models.PositiveIntegerField()),
                ('theoretical', models.PositiveIntegerField(null=True)),
                ('counted', models.PositiveIntegerField(null=True)),
                ('difference', models.IntegerField(null=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='stock.shift')),
            ],
        ),
        migrations.CreateModel(
            name='StockControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('revision', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'permissions': [('view_stock', 'Consultar stock'), ('manage_stock', 'Gestionar stock y turnos')],
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='stock_single_control')],
            },
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(models.Value(1), condition=models.Q(('closed_at__isnull', True)), name='stock_one_open_shift'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['product', 'created_at'], name='stock_movem_product_bbd07a_idx'),
        ),
        migrations.AddConstraint(
            model_name='movement',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'SALE')), fields=('order_item',), name='stock_sale_once'),
        ),
        migrations.AddConstraint(
            model_name='shiftitem',
            constraint=models.UniqueConstraint(fields=('shift', 'product'), name='stock_unique_shift_product'),
        ),
    ]
