# Generated by Django 6.1.1 on 2026-10-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='opening_notes',
            field=models.TextField(blank=True),
        ),
    ]
