# Generated by Django 6.1.1 on 2026-09-28 16:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='orden de visualización')),
                ('active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('KITCHEN', 'Cocina'), ('BAR', 'Barra'), ('DELIVERY', 'Entrega')], max_length=20, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'estación de preparación',
                'verbose_name_plural': 'estaciones de preparación',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('code__in', ['KITCHEN', 'BAR', 'DELIVERY'])), name='catalog_station_valid_code')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Código único del producto. Ejemplo: PROD-001.', max_length=50, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='precio de venta')),
                ('published', models.BooleanField(default=False, help_text='Habilita su publicación en el menú.', verbose_name='publicado')),
                ('available', models.BooleanField(default=True, help_text='Indica si actualmente puede pedirse.', verbose_name='disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='categoría')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.station', verbose_name='estación de preparación')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('sale_price__gte', 0)), name='catalog_product_price_nonnegative')],
            },
        ),
    ]
