# Generated by Django 6.1.1 on 2026-09-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Enlace directo a una imagen externa.', max_length=2045, verbose_name='URL de la imagen'),
        ),
    ]
