# Generated by Django 6.1.1 on 2026-10-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.TextField(blank=True, default='', help_text='Información verificada de alérgenos y posibles trazas. Vacío significa información no disponible, no ausencia de alérgenos.', verbose_name='alérgenos'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, default='', help_text='Ingredientes declarados por el restaurante. Puedes escribir uno por línea.', verbose_name='ingredientes'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutritional_information',
            field=models.TextField(blank=True, default='', help_text='Indica la porción de referencia, cantidades y unidades. No introduzcas valores estimados sin verificar.', verbose_name='información nutricional'),
        ),
    ]
