# Generated by Django 6.1.1 on 2026-10-02 19:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_product_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.UUIDField(editable=False, unique=True)),
                ('request_hash', models.CharField(editable=False, max_length=64)),
                ('customer_name', models.CharField(max_length=80)),
                ('fulfillment', models.CharField(choices=[('DINE_IN', 'En mesa'), ('PICKUP', 'Para recoger')], max_length=10)),
                ('table_label', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(default='DEMO_CONFIRMED', editable=False, max_length=20)),
                ('payment_status', models.CharField(default='SIMULATED', editable=False, max_length=20)),
                ('currency', models.CharField(default='PEN', editable=False, max_length=3)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='order_total_nonnegative'), models.CheckConstraint(condition=models.Q(('fulfillment__in', ['DINE_IN', 'PICKUP'])), name='order_valid_fulfillment')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('station_code', models.CharField(max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('order', 'product'), name='order_unique_product'), models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 99)), name='order_item_valid_quantity'), models.CheckConstraint(condition=models.Q(('line_total__gte', 0), ('unit_price__gte', 0)), name='order_item_nonnegative')],
            },
        ),
    ]
