# Generated by Django 6.1.1 on 2026-10-05 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_production_status_order_released_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('production_status__in', ['NOT_RELEASED', 'PENDING', 'IN_PROGRESS', 'READY', 'CANCELLED', 'PARTIALLY_CANCELLED'])), name='order_valid_production_status'),
        ),
    ]
