# Generated by Django 6.1.1 on 2026-10-06 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0002_recipe_ingredientrevision_recipeversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment', models.CharField(max_length=160)),
                ('department', models.CharField(max_length=100)),
                ('inventory_date', models.DateField(blank=True, null=True)),
                ('employee', models.CharField(max_length=160)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('is_example', models.BooleanField(default=False)),
                ('source_name', models.CharField(blank=True, max_length=250)),
                ('source_sheet', models.CharField(blank=True, max_length=100)),
                ('source_digest', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=60)),
                ('family', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('product', models.CharField(max_length=250)),
                ('unit', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=16)),
                ('source_row', models.PositiveIntegerField(null=True)),
                ('source_extra', models.JSONField(default=dict)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='costing.inventorycount')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
