# Generated by Django 6.1.1 on 2026-10-05 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_production_status_order_released_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(choices=[('KITCHEN', 'Cocina'), ('BAR', 'Barra')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En preparación'), ('READY', 'Listo'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('demo', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='orders.order')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'permissions': [('release_order', 'Puede liberar pedidos de demostración'), ('view_kitchen_ticket', 'Puede consultar tickets de cocina'), ('advance_kitchen_ticket', 'Puede avanzar tickets de cocina'), ('view_bar_ticket', 'Puede consultar tickets de barra'), ('advance_bar_ticket', 'Puede avanzar tickets de barra'), ('cancel_ticket', 'Puede cancelar tickets')],
            },
        ),
        migrations.CreateModel(
            name='ProductionTicketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_item', to='orders.orderitem')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='production.productionticket')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='production.productionticket')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='productionticket',
            constraint=models.UniqueConstraint(fields=('order', 'station_code'), name='ticket_unique_order_station'),
        ),
        migrations.AddConstraint(
            model_name='productionticket',
            constraint=models.CheckConstraint(condition=models.Q(('station_code__in', ['KITCHEN', 'BAR'])), name='ticket_valid_station'),
        ),
        migrations.AddConstraint(
            model_name='productionticket',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'IN_PROGRESS', 'READY', 'CANCELLED'])), name='ticket_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='productionticket',
            constraint=models.CheckConstraint(condition=models.Q(('demo', True)), name='ticket_demo_only'),
        ),
        migrations.AddConstraint(
            model_name='productionticketitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 99)), name='ticket_item_valid_quantity'),
        ),
    ]
