# Generated by Django 6.1.1 on 2026-10-05 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketevent',
            name='source',
            field=models.CharField(choices=[('STAFF', 'Personal'), ('CHECKOUT', 'Checkout automático')], default='STAFF', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
