# Generated by Django 6.1.1 on 2026-10-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_ticketevent_source_alter_ticketevent_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionticket',
            name='archived_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
