# Generated by Django 6.1.1 on 2026-10-05 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_cancellationrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellationrequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cancellationrequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_cancellations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cancellationrequest',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
